// ─── Grimoire · Theme ─────────────────────────────────────────────────────
// Design system: parchment / near-black, Cinzel display, Crimson Pro body,
// heraldic gold for high accents. Day and Night are locked brand language.

// Two modes — Day and Night (locked brand language, not system dark-mode).
// Night is not an inversion: surfaces go to deep ink-blue, text to warm
// parchment, but the accents stay *lit* — gold glows, oxblood/sage deepen.
// Candlelight in a dark room, not a greyscale flip.
export const THEME = {
  day: {
    bgFrame: "#2A2622",
    parchment: "#F4EFE4",
    parchmentDeep: "#EBE3D3",
    ink: "#1B1714",
    inkSoft: "#4A423A",
    gold: "#B08544",
    goldDeep: "#8A6630",
    oxblood: "#6E2A2A",
    sage: "#5B6650",
    hair: "#D8CDB8",
    glow: "transparent", // no halo by day
  },
  night: {
    bgFrame: "#08060B",
    parchment: "#15131C", // card/base surface
    parchmentDeep: "#1E1B27", // raised surface
    ink: "#EDE6D6", // primary text (warm parchment)
    inkSoft: "#9C93A8", // secondary text (muted lilac-grey)
    gold: "#E0B868", // lifted, luminous
    goldDeep: "#C99B4A",
    oxblood: "#B65555", // deepened but still lit against dark
    sage: "#8AA07E",
    hair: "#2C2838",
    glow: "rgba(224,184,104,0.35)", // accent halo by night
  },
};

export const FONTS = `
@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600&family=Crimson+Pro:ital,wght@0,400;0,500;1,400&display=swap');

@keyframes breathe {
  0%, 100% { transform: scale(1);   opacity: 0.85; }
  50%      { transform: scale(1.07); opacity: 1; }
}
@keyframes rise {
  0%   { transform: translateY(0)    scale(1);   opacity: 1; }
  60%  { transform: translateY(-26px) scale(1.1); opacity: 1; }
  100% { transform: translateY(-70px) scale(0.7); opacity: 0; }
}
@keyframes ringOut {
  0%   { transform: scale(0.6); opacity: 0.5; }
  100% { transform: scale(2.4); opacity: 0;   }
}
@keyframes fadeUp {
  from { opacity: 0; transform: translateY(8px); }
  to   { opacity: 1; transform: translateY(0); }
}
@keyframes settleIn {
  from { opacity: 0; transform: scale(0.92); }
  to   { opacity: 1; transform: scale(1); }
}
@keyframes sheetUp {
  from { transform: translateY(100%); }
  to   { transform: translateY(0); }
}
@media (prefers-reduced-motion: reduce) {
  * { animation-duration: 0.01ms !important; }
}
`;

export const seg = (active, C) => ({
  padding: "5px 12px",
  borderRadius: 7,
  border: "none",
  cursor: "pointer",
  fontSize: 12,
  fontFamily: "system-ui",
  fontWeight: 600,
  background: active ? C.ink : "transparent",
  color: active ? C.parchment : C.inkSoft,
});

export const makeStyles = (C, mode = "day") => {
  // The Apple Pay sheet is system UI — it renders dark in dark mode.
  const n = mode === "night";
  const sheet = {
    bg: n ? "#1C1C1E" : "#fff",
    text: n ? "#fff" : "#111",
    textDim: n ? "#8E8E93" : "#888",
    hair: n ? "#2C2C2E" : "#EEE",
    close: n ? "#2C2C2E" : "#EFEFEF",
    closeText: n ? "#aaa" : "#555",
    btnBg: n ? "#fff" : "#000",
    btnText: n ? "#000" : "#fff",
    hint: n ? "#7C7C82" : "#999",
  };
  return {
  frame: {
    minHeight: "100vh",
    background: C.bgFrame,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px 16px",
    fontFamily: "'Crimson Pro', Georgia, serif",
    transition: "background 0.5s ease",
  },
  switcher: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: C.parchment,
    padding: "6px 8px",
    borderRadius: 10,
    marginBottom: 18,
  },
  switcherLabel: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: C.inkSoft,
    fontFamily: "system-ui",
    fontWeight: 600,
    marginRight: 2,
  },
  tapCount: {
    fontSize: 11,
    color: C.goldDeep,
    fontFamily: "system-ui",
    fontWeight: 700,
    marginLeft: 4,
    minWidth: 44,
  },
  phone: {
    width: 360,
    maxWidth: "100%",
    height: 720,
    maxHeight: "85vh",
    background: C.parchment,
    borderRadius: 28,
    boxShadow: "0 24px 60px rgba(0,0,0,0.45)",
    transition: "background 0.5s ease",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  viewport: {
    flex: 1,
    overflowY: "auto",
    padding: "26px 20px 16px",
  },
  tabBar: {
    display: "flex",
    borderTop: `1px solid ${C.hair}`,
    background: C.parchment,
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  tabBtn: {
    flex: 1,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "10px 0 12px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    fontFamily: "'Crimson Pro', Georgia, serif",
  },
  tabGlyph: { fontSize: 18, lineHeight: 1, transition: "color 0.3s ease" },
  tabLabel: {
    fontFamily: "system-ui",
    fontSize: 11,
    letterSpacing: 0.3,
    transition: "color 0.3s ease",
  },
  todayHead: { marginBottom: 20 },
  headRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  themeToggle: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    border: `1px solid ${C.hair}`,
    background: "transparent",
    color: C.gold,
    fontSize: 17,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
    transition: "all 0.3s ease",
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: C.inkSoft,
    fontFamily: "system-ui",
    fontWeight: 600,
  },
  todayTitle: {
    fontFamily: "'Cinzel', serif",
    fontSize: 30,
    color: C.ink,
    fontWeight: 600,
    marginTop: 2,
  },
  card: {
    background: C.parchmentDeep,
    borderRadius: 18,
    borderTop: "3px solid",
    padding: "22px 20px 20px",
    boxShadow: "0 2px 0 rgba(0,0,0,0.04)",
    transition: "background 0.5s ease",
  },
  cardEyebrow: {
    fontSize: 11.5,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: C.goldDeep,
    fontFamily: "system-ui",
    fontWeight: 700,
  },
  glyphWrap: { textAlign: "center", margin: "10px 0 4px" },
  glyph: { fontSize: 52, lineHeight: 1 },
  cardTitle: {
    fontFamily: "'Cinzel', serif",
    fontSize: 23,
    color: C.ink,
    fontWeight: 600,
    textAlign: "center",
    marginTop: 6,
  },
  cardSub: {
    fontSize: 16,
    fontStyle: "italic",
    color: C.inkSoft,
    textAlign: "center",
    marginTop: 4,
  },
  rationale: {
    fontSize: 14.5,
    lineHeight: 1.45,
    color: C.inkSoft,
    textAlign: "center",
    margin: "14px 6px 18px",
  },
  castBtn: {
    width: "100%",
    background: C.ink,
    color: C.parchment,
    border: "none",
    borderRadius: 13,
    padding: "15px 18px",
    fontSize: 17,
    fontFamily: "'Cinzel', serif",
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  // Apple Pay
  paySheet: {
    background: sheet.bg,
    borderRadius: 14,
    padding: "16px 16px 14px",
    boxShadow: "0 8px 30px rgba(0,0,0,0.18)",
  },
  payTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  payMark: {
    fontFamily: "system-ui",
    fontWeight: 600,
    fontSize: 17,
    color: sheet.text,
  },
  payClose: {
    border: "none",
    background: sheet.close,
    width: 26,
    height: 26,
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: 12,
    color: sheet.closeText,
  },
  payRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: `1px solid ${sheet.hair}`,
    fontFamily: "system-ui",
    fontSize: 14,
  },
  payLabel: { color: sheet.textDim },
  payVal: { color: sheet.text, fontWeight: 500 },
  payTotal: { color: sheet.text, fontWeight: 700 },
  payConfirm: {
    width: "100%",
    background: sheet.btnBg,
    color: sheet.btnText,
    border: "none",
    borderRadius: 11,
    padding: "13px",
    fontSize: 16,
    fontFamily: "system-ui",
    fontWeight: 600,
    cursor: "pointer",
    marginTop: 14,
  },
  payHint: {
    textAlign: "center",
    fontSize: 12,
    color: sheet.hint,
    fontFamily: "system-ui",
    marginTop: 8,
  },
  // Success
  success: {
    textAlign: "center",
    padding: "10px 0 4px",
    animation: "settleIn 0.6s ease both",
  },
  successGlyph: {
    fontSize: 46,
    animation: "settleIn 0.7s ease both",
  },
  successKicker: {
    fontFamily: "'Cinzel', serif",
    fontSize: 21,
    color: C.ink,
    fontWeight: 600,
    marginTop: 8,
    letterSpacing: 0.5,
  },
  successSub: {
    fontSize: 15,
    color: C.inkSoft,
    margin: "10px 18px 20px",
    lineHeight: 1.5,
    fontStyle: "italic",
  },
  ghostBtn: {
    background: "transparent",
    border: `1px solid ${C.hair}`,
    color: C.inkSoft,
    borderRadius: 11,
    padding: "11px 18px",
    fontSize: 14,
    fontFamily: "system-ui",
    fontWeight: 600,
    cursor: "pointer",
  },

  // ── Casting card + held beat ──────────────────────────
  cardBody: { transition: "opacity 0.7s ease" },
  cardBodyMuted: { opacity: 0.32 },
  cardCasting: {
    boxShadow: "0 0 0 1px rgba(0,0,0,0.04), 0 10px 40px rgba(0,0,0,0.10)",
    transition: "box-shadow 0.7s ease",
  },
  beat: {
    textAlign: "center",
    padding: "8px 0 6px",
  },
  beatGlyphWrap: {
    position: "relative",
    height: 110,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  beatGlyph: {
    fontSize: 58,
    lineHeight: 1,
    position: "relative",
    zIndex: 2,
  },
  beatGlyphHold: { animation: "breathe 2.2s ease-in-out infinite" },
  beatGlyphSend: { animation: "rise 1.4s cubic-bezier(.4,0,.2,1) forwards" },
  ring: {
    position: "absolute",
    width: 64,
    height: 64,
    borderRadius: "50%",
    border: "1.5px solid",
    opacity: 0,
    zIndex: 1,
  },
  ring2: { width: 90, height: 90 },
  ringSend: { animation: "ringOut 1.3s ease-out forwards" },
  ringSend2: { animation: "ringOut 1.3s ease-out 0.15s forwards" },
  beatWord: {
    fontFamily: "system-ui",
    fontSize: 12,
    letterSpacing: 3,
    textTransform: "uppercase",
    color: C.inkSoft,
    marginTop: 10,
    animation: "fadeUp 0.6s ease both",
  },

  // ── Modules container ──────────────────────────
  modules: {
    marginTop: 16,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    transition: "opacity 0.5s ease",
  },
  modulesMuted: { opacity: 0.25, pointerEvents: "none" },

  // shared module shell
  module: {
    width: "100%",
    background: C.parchmentDeep,
    border: `1px solid ${C.hair}`,
    borderRadius: 16,
    padding: "14px 16px",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "'Crimson Pro', Georgia, serif",
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  moduleHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  moduleEyebrow: {
    fontFamily: "system-ui",
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    fontWeight: 700,
    color: C.inkSoft,
  },
  moduleLink: {
    fontFamily: "system-ui",
    fontSize: 12,
    color: C.goldDeep,
    fontWeight: 600,
  },
  moduleFree: {
    fontFamily: "system-ui",
    fontSize: 10.5,
    letterSpacing: 1,
    textTransform: "uppercase",
    fontWeight: 700,
    color: C.sage,
    border: `1px solid ${C.hair}`,
    borderRadius: 20,
    padding: "2px 8px",
  },

  // Personal strip
  strip: {
    width: "100%",
    background: C.parchmentDeep,
    border: `1px solid ${C.hair}`,
    borderRadius: 16,
    padding: "12px 16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    cursor: "pointer",
    fontFamily: "'Crimson Pro', Georgia, serif",
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  stripRank: { display: "flex", alignItems: "center", gap: 12, flex: 1 },
  stripNumeral: {
    fontFamily: "'Cinzel', serif",
    fontSize: 26,
    fontWeight: 600,
    minWidth: 26,
    textAlign: "center",
  },
  stripRankText: { flex: 1 },
  stripRankName: {
    fontFamily: "'Cinzel', serif",
    fontSize: 15,
    color: C.ink,
    fontWeight: 600,
  },
  stripProgressTrack: {
    height: 4,
    background: C.hair,
    borderRadius: 4,
    margin: "5px 0 3px",
    overflow: "hidden",
  },
  stripProgressFill: { height: "100%", borderRadius: 4 },
  stripNext: {
    fontFamily: "system-ui",
    fontSize: 11,
    color: C.inkSoft,
  },
  stripCoins: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    paddingLeft: 14,
    borderLeft: `1px solid ${C.hair}`,
    marginLeft: 14,
  },
  coinGlyph: { fontSize: 15 },
  coinAmount: {
    fontFamily: "system-ui",
    fontWeight: 700,
    fontSize: 16,
    color: C.ink,
  },

  // Daily card
  cardDrawn: { display: "flex", alignItems: "center", gap: 12 },
  tarotGlyph: { fontSize: 30 },
  tarotName: {
    fontFamily: "'Cinzel', serif",
    fontSize: 16,
    color: C.ink,
    fontWeight: 600,
  },
  tarotMeaning: {
    fontSize: 14,
    fontStyle: "italic",
    color: C.inkSoft,
    marginTop: 1,
  },
  cardUndrawn: { display: "flex", alignItems: "center", gap: 12 },
  cardBack: {
    width: 38,
    height: 52,
    borderRadius: 6,
    border: "1.5px solid",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
  },
  undrawnText: {
    fontFamily: "'Cinzel', serif",
    fontSize: 15,
    color: C.ink,
    fontWeight: 500,
  },

  // Community feed
  feedList: { display: "flex", flexDirection: "column", gap: 9 },
  feedRow: { display: "flex", alignItems: "center", gap: 9 },
  feedDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    flexShrink: 0,
  },
  feedText: { fontSize: 14.5, color: C.inkSoft, flex: 1, lineHeight: 1.3 },
  feedWho: { color: C.ink, fontWeight: 600 },
  feedWhen: {
    fontFamily: "system-ui",
    fontSize: 11,
    color: C.inkSoft,
    flexShrink: 0,
  },

  // Featured practitioners
  featRow: { display: "flex", gap: 9 },
  featCard: {
    flex: 1,
    background: C.parchment,
    border: `1px solid ${C.hair}`,
    borderRadius: 12,
    padding: "12px 8px",
    textAlign: "center",
    cursor: "pointer",
    fontFamily: "'Crimson Pro', Georgia, serif",
    transition: "background 0.5s ease",
  },
  featGlyph: { fontSize: 22 },
  featName: {
    fontFamily: "'Cinzel', serif",
    fontSize: 12.5,
    color: C.ink,
    fontWeight: 600,
    marginTop: 5,
    lineHeight: 1.15,
  },
  featCraft: {
    fontSize: 11.5,
    color: C.inkSoft,
    marginTop: 2,
    lineHeight: 1.2,
  },
  featRate: {
    fontFamily: "system-ui",
    fontSize: 10.5,
    fontWeight: 700,
    marginTop: 6,
  },

  // ── Browse ──────────────────────────────────────
  searchWrap: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: C.parchmentDeep,
    border: `1px solid ${C.hair}`,
    borderRadius: 12,
    padding: "10px 14px",
    marginBottom: 14,
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  searchGlyph: { fontSize: 16, color: C.inkSoft },
  searchInput: {
    flex: 1,
    border: "none",
    background: "transparent",
    outline: "none",
    fontFamily: "'Crimson Pro', Georgia, serif",
    fontSize: 16,
    color: C.ink,
  },
  chipRow: {
    display: "flex",
    gap: 8,
    overflowX: "auto",
    paddingBottom: 4,
    marginBottom: 16,
  },
  chip: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 5,
    background: C.parchmentDeep,
    border: `1px solid ${C.hair}`,
    borderRadius: 20,
    padding: "7px 13px",
    fontFamily: "'Crimson Pro', Georgia, serif",
    fontSize: 14,
    color: C.ink,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "background 0.2s ease, border-color 0.2s ease",
  },
  chipGlyph: { fontSize: 13 },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  gridCard: {
    background: C.parchmentDeep,
    border: `1px solid ${C.hair}`,
    borderRadius: 14,
    padding: "14px 12px 12px",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "'Crimson Pro', Georgia, serif",
    display: "flex",
    flexDirection: "column",
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  gridGlyph: { fontSize: 26, marginBottom: 8 },
  gridTitle: {
    fontFamily: "'Cinzel', serif",
    fontSize: 14.5,
    color: C.ink,
    fontWeight: 600,
    lineHeight: 1.2,
  },
  gridSub: {
    fontSize: 13.5,
    fontStyle: "italic",
    color: C.inkSoft,
    marginTop: 3,
    lineHeight: 1.3,
    flex: 1,
  },
  gridFoot: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 10,
  },
  gridRate: { fontFamily: "system-ui", fontSize: 10.5, fontWeight: 700 },
  gridPrice: {
    fontFamily: "system-ui",
    fontSize: 14,
    fontWeight: 700,
    color: C.ink,
  },
  emptyState: { textAlign: "center", padding: "48px 20px" },
  emptyGlyph: { fontSize: 34, color: C.inkSoft },
  emptyText: {
    fontSize: 15,
    fontStyle: "italic",
    color: C.inkSoft,
    marginTop: 10,
  },

  // ── Cast sheet (Browse → cast) ──────────────────
  sheetScrim: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "flex-end",
    borderRadius: 28,
    zIndex: 10,
  },
  sheet: {
    width: "100%",
    background: C.parchment,
    borderRadius: "22px 22px 28px 28px",
    padding: "10px 18px 24px",
    boxShadow: "0 -12px 40px rgba(0,0,0,0.25)",
    transition: "background 0.5s ease",
    animation: "sheetUp 0.32s cubic-bezier(.2,.7,.2,1) both",
  },
  sheetGrip: {
    width: 38,
    height: 4,
    borderRadius: 4,
    background: C.hair,
    margin: "0 auto 8px",
  },

  // ── Coven ───────────────────────────────────────
  inviteBtn: {
    background: "transparent",
    border: `1px solid ${C.hair}`,
    color: C.ink,
    borderRadius: 20,
    padding: "8px 14px",
    fontSize: 13,
    fontFamily: "'Cinzel', serif",
    fontWeight: 500,
    cursor: "pointer",
    transition: "border-color 0.5s ease, color 0.5s ease",
  },
  testimonyWrap: {
    background: C.parchmentDeep,
    border: `1px solid ${C.hair}`,
    borderRadius: 16,
    padding: "14px 16px",
    marginBottom: 18,
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  testimony: { marginTop: 10 },
  testimonyNote: {
    fontSize: 16,
    fontStyle: "italic",
    color: C.ink,
    lineHeight: 1.4,
  },
  testimonyMeta: {
    fontFamily: "system-ui",
    fontSize: 11.5,
    color: C.inkSoft,
    marginTop: 4,
  },
  testimonyWho: { color: C.ink, fontWeight: 600 },
  covenLabel: { marginBottom: 10 },
  covenList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  covenRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 4px",
    borderBottom: `1px solid ${C.hair}`,
    transition: "border-color 0.5s ease",
  },
  covenGlyph: { fontSize: 22, width: 24, textAlign: "center", flexShrink: 0 },
  covenMid: { flex: 1, minWidth: 0 },
  covenNameRow: { display: "flex", alignItems: "center", gap: 7 },
  covenName: {
    fontFamily: "'Cinzel', serif",
    fontSize: 15,
    color: C.ink,
    fontWeight: 600,
  },
  covenBadge: {
    fontFamily: "system-ui",
    fontSize: 10,
    fontWeight: 700,
    border: "1px solid",
    borderRadius: 20,
    padding: "1px 6px",
  },
  covenLast: {
    fontSize: 13,
    color: C.inkSoft,
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  covenNumeral: {
    fontFamily: "'Cinzel', serif",
    fontWeight: 600,
  },
  castWithBtn: {
    background: "transparent",
    border: "1px solid",
    borderRadius: 20,
    padding: "6px 16px",
    fontFamily: "'Cinzel', serif",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    flexShrink: 0,
  },
  covenRank: {
    fontFamily: "system-ui",
    fontSize: 12,
    flexShrink: 0,
  },
  findMore: {
    width: "100%",
    background: "transparent",
    border: `1px dashed ${C.hair}`,
    color: C.goldDeep,
    borderRadius: 14,
    padding: "13px",
    marginTop: 18,
    fontFamily: "'Crimson Pro', Georgia, serif",
    fontSize: 14.5,
    cursor: "pointer",
    transition: "border-color 0.5s ease",
  },

  // ── You ─────────────────────────────────────────
  youCrest: {
    textAlign: "center",
    background: C.parchmentDeep,
    border: `1px solid ${C.hair}`,
    borderRadius: 18,
    padding: "22px 20px 18px",
    marginBottom: 12,
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  youNumeral: {
    fontFamily: "'Cinzel', serif",
    fontSize: 44,
    fontWeight: 600,
    lineHeight: 1,
  },
  youRankName: {
    fontFamily: "'Cinzel', serif",
    fontSize: 20,
    color: C.ink,
    fontWeight: 600,
    marginTop: 4,
  },
  youProgressTrack: {
    height: 5,
    background: C.hair,
    borderRadius: 5,
    margin: "14px 0 6px",
    overflow: "hidden",
  },
  youProgressFill: { height: "100%", borderRadius: 5 },
  youNext: { fontFamily: "system-ui", fontSize: 12, color: C.inkSoft },
  youStats: {
    display: "flex",
    gap: 10,
    marginBottom: 20,
  },
  youStat: {
    flex: 1,
    background: C.parchmentDeep,
    border: `1px solid ${C.hair}`,
    borderRadius: 14,
    padding: "14px 12px",
    textAlign: "center",
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  youStatNum: {
    fontFamily: "system-ui",
    fontSize: 20,
    fontWeight: 700,
  },
  youStatLabel: {
    fontFamily: "system-ui",
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: C.inkSoft,
    fontWeight: 600,
    marginTop: 3,
  },
  youStatSub: {
    fontFamily: "system-ui",
    fontSize: 11,
    color: C.inkSoft,
    marginTop: 5,
  },
  topUpBtn: {
    background: "transparent",
    border: "1px solid",
    borderRadius: 20,
    padding: "4px 12px",
    fontSize: 12,
    fontFamily: "'Cinzel', serif",
    fontWeight: 500,
    cursor: "pointer",
    marginTop: 7,
  },
  histRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 4px",
    borderBottom: `1px solid ${C.hair}`,
    transition: "border-color 0.5s ease",
  },
  verdictBtns: { display: "flex", gap: 6, flexShrink: 0 },
  verdictYes: {
    background: "transparent",
    border: "1px solid",
    borderRadius: 20,
    padding: "5px 12px",
    fontSize: 12.5,
    fontFamily: "'Cinzel', serif",
    fontWeight: 500,
    cursor: "pointer",
  },
  verdictNo: {
    background: "transparent",
    border: "1px solid",
    borderRadius: 20,
    padding: "5px 12px",
    fontSize: 12.5,
    fontFamily: "'Cinzel', serif",
    fontWeight: 500,
    cursor: "pointer",
  },
  verdictTag: {
    fontFamily: "system-ui",
    fontSize: 12.5,
    fontWeight: 600,
    flexShrink: 0,
  },
  };
};
