import { TYPE } from "./fonts.js";
// ─── Grimoire · shell styles ─────────────────────────────────────────────
// Frame, phone, viewport, tab bar, hero card, cast button.
// Receives the active palette (C) — plus the system-sheet palette where the
// surface needs it. Returns a flat slice of the composed style object.

export const shellStyles = (sheet) => ({
  frame: {
    minHeight: "100vh",
    background: "var(--p-desk)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px 16px",
    fontFamily: TYPE.body,
    transition: "background 0.5s ease",
  },
  switcher: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    // Wraps — the palette axis added four more controls and a single row
    // runs off a phone-width viewport. Dev UI, stripped before launch.
    flexWrap: "wrap",
    gap: 6,
    maxWidth: 380,
    background: "var(--p-ground)",
    padding: "6px 8px",
    borderRadius: 10,
    marginBottom: 18,
  },
  switcherLabel: {
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "var(--p-textSoft)",
    fontFamily: TYPE.ui,
    fontWeight: 600,
    marginRight: 2,
  },
  tapCount: {
    fontSize: 12,
    color: "var(--p-litDeep)",
    fontFamily: TYPE.ui,
    fontWeight: 700,
    marginLeft: 4,
    minWidth: 44,
  },
  phone: {
    width: 360,
    maxWidth: "100%",
    height: 720,
    maxHeight: "85vh",
    background: "var(--p-ground)",
    borderRadius: 28,
    boxShadow: "0 24px 60px rgba(0,0,0,0.45)",
    transition: "background 0.5s ease",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  viewport: {
    flex: 1,
    overflowY: "auto",
    padding: "26px 20px 16px",
  },
  tabBar: {
    display: "flex",
    borderTop: `1px solid var(--p-hair)`,
    background: "var(--p-ground)",
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  tabBtn: {
    flex: 1,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "10px 0 12px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    fontFamily: TYPE.body,
  },
  tabGlyph: { fontSize: 19, lineHeight: 1, transition: "color 0.3s ease" },
  tabLabel: {
    fontFamily: TYPE.ui,
    fontSize: 12,
    letterSpacing: 0.3,
    transition: "color 0.3s ease",
  },
  todayHead: { marginBottom: 20 },
  headRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  themeToggle: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    border: `1px solid var(--p-hair)`,
    background: "transparent",
    color: "var(--p-accent)",
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
    transition: "all 0.3s ease",
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: "var(--p-textSoft)",
    fontFamily: TYPE.ui,
    fontWeight: 600,
  },
  todayTitle: {
    fontFamily: TYPE.display,
    fontSize: 30,
    color: "var(--p-text)",
    fontWeight: 600,
    marginTop: 2,
  },
  card: {
    background: "var(--p-plate1)",
    borderRadius: 18,
    borderTop: "3px solid",
    padding: "22px 20px 20px",
    boxShadow: "0 2px 0 rgba(0,0,0,0.04)",
    transition: "background 0.5s ease",
  },
  cardEyebrow: {
    fontSize: 12,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: "var(--p-litDeep)",
    fontFamily: TYPE.ui,
    fontWeight: 700,
  },
  glyphWrap: { textAlign: "center", margin: "10px 0 4px" },
  glyph: { fontSize: 44, lineHeight: 1 },
  cardTitle: {
    fontFamily: TYPE.display,
    fontSize: 22,
    color: "var(--p-text)",
    fontWeight: 600,
    textAlign: "center",
    marginTop: 6,
  },
  cardSub: {
    fontSize: 16,
    color: "var(--p-textSoft)",
    textAlign: "center",
    marginTop: 4,
  },
  rationale: {
    fontSize: 14,
    lineHeight: 1.45,
    color: "var(--p-textSoft)",
    textAlign: "center",
    margin: "14px 6px 18px",
  },
  castBtn: {
    width: "100%",
    background: "var(--p-text)",
    color: "var(--p-ground)",
    border: "none",
    borderRadius: 13,
    padding: "15px 18px",
    fontSize: 16,
    fontFamily: TYPE.display,
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  // Apple Pay
  paySheet: {
    background: sheet.bg,
    borderRadius: 14,
    padding: "16px 16px 14px",
    boxShadow: "0 8px 30px rgba(0,0,0,0.18)",
  },
  payTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  payMark: {
    fontFamily: TYPE.ui,
    fontWeight: 600,
    fontSize: 16,
    color: sheet.text,
  },
  payClose: {
    border: "none",
    background: sheet.close,
    width: 26,
    height: 26,
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: 12,
    color: sheet.closeText,
  },
  payRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: `1px solid ${sheet.hair}`,
    fontFamily: TYPE.ui,
    fontSize: 14,
  },
  payLabel: { color: sheet.textDim },
  payVal: { color: sheet.text, fontWeight: 500 },
  payTotal: { color: sheet.text, fontWeight: 700 },
  payConfirm: {
    width: "100%",
    background: sheet.btnBg,
    color: sheet.btnText,
    border: "none",
    borderRadius: 11,
    padding: "13px",
    fontSize: 16,
    fontFamily: TYPE.ui,
    fontWeight: 600,
    cursor: "pointer",
    marginTop: 14,
  },
  payHint: {
    textAlign: "center",
    fontSize: 12,
    color: sheet.hint,
    fontFamily: TYPE.ui,
    marginTop: 8,
  },
  // Success
  success: {
    textAlign: "center",
    padding: "10px 0 4px",
    animation: "settleIn 0.6s ease both",
  },
  successGlyph: {
    fontSize: 44,
    animation: "settleIn 0.7s ease both",
  },
  successKicker: {
    fontFamily: TYPE.display,
    fontSize: 22,
    color: "var(--p-text)",
    fontWeight: 600,
    marginTop: 8,
    letterSpacing: 0.5,
  },
  successSub: {
    fontSize: 16,
    color: "var(--p-textSoft)",
    margin: "10px 18px 20px",
    lineHeight: 1.5,
  },
  ghostBtn: {
    background: "transparent",
    border: `1px solid var(--p-hair)`,
    color: "var(--p-textSoft)",
    borderRadius: 11,
    padding: "11px 18px",
    fontSize: 14,
    fontFamily: TYPE.ui,
    fontWeight: 600,
    cursor: "pointer",
  }
});
