import { TYPE } from "./fonts.js";
// ─── Grimoire · shell styles ─────────────────────────────────────────────
// Frame, phone, viewport, tab bar, hero card, cast button.
// Receives the active palette (C) — plus the system-sheet palette where the
// surface needs it. Returns a flat slice of the composed style object.

export const shellStyles = (sheet) => ({
  frame: {
    minHeight: "100vh",
    background: "var(--p-desk)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px 16px",
    fontFamily: TYPE.body,
    transition: "background 0.5s ease",
  },
  switcher: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    // Wraps — the palette axis added four more controls and a single row
    // runs off a phone-width viewport. Dev UI, stripped before launch.
    flexWrap: "wrap",
    gap: 6,
    maxWidth: 380,
    background: "var(--p-ground)",
    padding: "6px 8px",
    borderRadius: 10,
    marginBottom: 18,
  },
  switcherLabel: {
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "var(--p-textSoft)",
    fontFamily: TYPE.ui,
    fontWeight: 600,
    marginRight: 2,
  },
  tapCount: {
    fontSize: 12,
    color: "var(--p-litDeep)",
    fontFamily: TYPE.ui,
    fontWeight: 700,
    marginLeft: 4,
    minWidth: 44,
  },
  phone: {
    width: 390,
    maxWidth: "100%",
    height: 844,
    maxHeight: "88vh",
    background: "var(--p-ground)",
    borderRadius: 48,               // --r-sheet
    border: "1px solid var(--p-frameBorder)",
    boxShadow: "0 40px 80px -24px rgba(0,0,0,0.55)",
    transition: "background 0.5s ease",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    position: "relative",
  },
  // Ambient glow. Two blurred orbs sitting behind the content are most of
  // what gives the prototype its depth — without them the ground reads flat
  // and every card has to carry the atmosphere on its own.
  glowA: {
    position: "absolute", width: 300, height: 300, borderRadius: "50%",
    background: "var(--p-glow1)", filter: "blur(80px)", opacity: 0.33,
    top: -70, right: -90, pointerEvents: "none",
  },
  glowB: {
    position: "absolute", width: 300, height: 300, borderRadius: "50%",
    background: "var(--p-glow2)", filter: "blur(85px)", opacity: 0.25,
    top: 340, left: -100, pointerEvents: "none",
  },
  viewport: {
    flex: 1,
    overflowY: "auto",
    padding: "34px 23px 26px",
    position: "relative",           // above the glow
  },
  tabBar: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    margin: "0 16px 14px",
    padding: 5,
    borderRadius: 100,              // --r-pill
    background: "var(--p-glass)",
    border: "1px solid var(--p-glassBorder)",
    boxShadow: "var(--p-cardShadow)",
    position: "relative",
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  tabBtn: {
    flex: 1,
    background: "transparent",
    border: "none",
    borderRadius: 100,
    cursor: "pointer",
    padding: "9px 0 10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    fontFamily: TYPE.body,
  },
  tabGlyph: { fontSize: 14, lineHeight: 1, transition: "color 0.3s ease" },
  tabBtnActive: { background: "var(--p-accentSoft)" },
  tabLabel: {
    fontFamily: TYPE.ui,
    fontSize: 10,
    letterSpacing: 0.4,
    transition: "color 0.3s ease",
  },
  todayHead: { marginBottom: 30 },
  headRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  themeToggle: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    border: `1px solid var(--p-hair)`,
    background: "transparent",
    color: "var(--p-accent)",
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
    transition: "all 0.3s ease",
  },
  // Eyebrow — DESIGN.md §6: uppercase, 9–10px, tracking 0.22–0.32em.
  eyebrow: {
    fontSize: 10,
    letterSpacing: "0.22em",
    lineHeight: 1.5,
    textTransform: "uppercase",
    color: "var(--p-text)",
    opacity: 0.6,
    fontFamily: TYPE.ui,
    fontWeight: 600,
  },
  todayTitle: {
    fontFamily: TYPE.display,
    fontSize: 44,                   // --t-title. The one thing that dominates.
    lineHeight: 1,
    letterSpacing: "-0.01em",       // --track-tight
    color: "var(--p-text)",
    fontWeight: 500,
  },
  greeting: {
    fontFamily: TYPE.display,
    fontSize: 16,
    color: "var(--p-text)",
    opacity: 0.75,
    marginTop: 8,
    marginBottom: 10,
  },
  card: {
    background: "var(--p-glass)",
    borderRadius: 20,               // --r-xl
    border: "1px solid var(--p-glassBorder)",
    padding: "12px 12px 14px",
    boxShadow: "var(--p-cardShadow)",
    transition: "background 0.5s ease",
  },
  // The image well at the head of the folio — the prototype's hero card
  // leads with a plate, not text. Empty until artwork exists.
  folioWell: {
    height: 150,
    borderRadius: 20,
    background: "var(--p-plate2)",
    border: "1px solid var(--p-hair)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  folioWellGlyph: { fontSize: 44, lineHeight: 1, color: "var(--p-accent)", opacity: 0.55 },
  folioMetaRow: {
    display: "flex", justifyContent: "space-between", alignItems: "flex-start",
    gap: 12, padding: "0 6px", marginBottom: 16,
  },
  folioLink: {
    fontFamily: TYPE.ui, fontSize: 10, fontWeight: 600,
    letterSpacing: "0.14em", textTransform: "uppercase",
    color: "var(--p-accent)", whiteSpace: "nowrap",
  },
  cardInner: { padding: "0 6px" },
  cardEyebrow: {
    fontSize: 10,
    flex: 1,
    minWidth: 0,
    lineHeight: 1.6,                // a wrapped eyebrow shouldn't crowd the title
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: "var(--p-text)",
    opacity: 0.6,
    fontFamily: TYPE.ui,
    fontWeight: 600,
  },
  glyphWrap: { textAlign: "center", margin: "10px 0 4px" },
  glyph: { fontSize: 44, lineHeight: 1 },
  cardTitle: {
    fontFamily: TYPE.display,
    fontSize: 30,                   // --t-h1
    lineHeight: 1.02,
    letterSpacing: "-0.01em",
    color: "var(--p-text)",
    fontWeight: 500,
    marginTop: 4,
  },
  cardSub: {
    fontFamily: TYPE.body,
    fontSize: 16,
    lineHeight: 1.4,
    color: "var(--p-text)",
    opacity: 0.75,
    marginTop: 8,
  },
  rationale: {
    fontFamily: TYPE.body,
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--p-text)",
    opacity: 0.6,
    margin: "12px 0 16px",
  },
  castBtn: {
    width: "100%",
    background: "var(--p-ctaBg)",
    color: "var(--p-ctaGold)",
    border: "none",
    borderRadius: 100,              // --r-pill
    padding: 17,
    fontSize: 12,
    letterSpacing: "0.14em",        // --track-wider
    textTransform: "uppercase",
    fontFamily: TYPE.ui,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  // Apple Pay
  paySheet: {
    background: sheet.bg,
    borderRadius: 14,
    padding: "16px 16px 14px",
    boxShadow: "0 8px 30px rgba(0,0,0,0.18)",
  },
  payTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  payMark: {
    fontFamily: TYPE.ui,
    fontWeight: 600,
    fontSize: 16,
    color: sheet.text,
  },
  payClose: {
    border: "none",
    background: sheet.close,
    width: 26,
    height: 26,
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: 12,
    color: sheet.closeText,
  },
  payRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: `1px solid ${sheet.hair}`,
    fontFamily: TYPE.ui,
    fontSize: 14,
  },
  payLabel: { color: sheet.textDim },
  payVal: { color: sheet.text, fontWeight: 500 },
  payTotal: { color: sheet.text, fontWeight: 700 },
  payConfirm: {
    width: "100%",
    background: sheet.btnBg,
    color: sheet.btnText,
    border: "none",
    borderRadius: 11,
    padding: "13px",
    fontSize: 16,
    fontFamily: TYPE.ui,
    fontWeight: 600,
    cursor: "pointer",
    marginTop: 14,
  },
  payHint: {
    textAlign: "center",
    fontSize: 12,
    color: sheet.hint,
    fontFamily: TYPE.ui,
    marginTop: 8,
  },
  // Success
  success: {
    textAlign: "center",
    padding: "10px 0 4px",
    animation: "settleIn 0.6s ease both",
  },
  successGlyph: {
    fontSize: 44,
    animation: "settleIn 0.7s ease both",
  },
  successKicker: {
    fontFamily: TYPE.display,
    fontSize: 22,
    color: "var(--p-text)",
    fontWeight: 600,
    marginTop: 8,
    letterSpacing: 0.5,
  },
  successSub: {
    fontSize: 16,
    color: "var(--p-textSoft)",
    margin: "10px 18px 20px",
    lineHeight: 1.5,
  },
  ghostBtn: {
    background: "transparent",
    border: `1px solid var(--p-hair)`,
    color: "var(--p-textSoft)",
    borderRadius: 11,
    padding: "11px 18px",
    fontSize: 14,
    fontFamily: TYPE.ui,
    fontWeight: 600,
    cursor: "pointer",
  }
});
