import { TYPE } from "./fonts.js";
// ─── Grimoire · you styles ─────────────────────────────────────────────
// Crest, rank progress, cast history.
// Receives the active palette (C) — plus the system-sheet palette where the
// surface needs it. Returns a flat slice of the composed style object.

export const youStyles = () => ({
  // ── You ─────────────────────────────────────────
  youCrest: {
    textAlign: "center",
    background: "var(--p-plate1)",
    border: `1px solid var(--p-hair)`,
    borderRadius: 18,
    padding: "22px 20px 18px",
    marginBottom: 12,
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  youNumeral: {
    fontFamily: TYPE.display,
    fontSize: 44,
    fontWeight: 600,
    lineHeight: 1,
  },
  youRankName: {
    fontFamily: TYPE.display,
    fontSize: 19,
    color: "var(--p-text)",
    fontWeight: 600,
    marginTop: 4,
  },
  youProgressTrack: {
    height: 5,
    background: "var(--p-hair)",
    borderRadius: 5,
    margin: "14px 0 6px",
    overflow: "hidden",
  },
  youProgressFill: { height: "100%", borderRadius: 5 },
  youNext: { fontFamily: TYPE.ui, fontSize: 12, color: "var(--p-textSoft)" },
  youStats: {
    display: "flex",
    gap: 10,
    marginBottom: 20,
  },
  youStat: {
    flex: 1,
    background: "var(--p-plate1)",
    border: `1px solid var(--p-hair)`,
    borderRadius: 14,
    padding: "14px 12px",
    textAlign: "center",
    transition: "background 0.5s ease, border-color 0.5s ease",
  },
  youStatNum: {
    fontFamily: TYPE.ui,
    fontSize: 19,
    fontWeight: 700,
  },
  youStatLabel: {
    fontFamily: TYPE.ui,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "var(--p-textSoft)",
    fontWeight: 600,
    marginTop: 3,
  },
  youStatSub: {
    fontFamily: TYPE.ui,
    fontSize: 12,
    color: "var(--p-textSoft)",
    marginTop: 5,
  },
  topUpBtn: {
    background: "transparent",
    border: "1px solid",
    borderRadius: 20,
    padding: "4px 12px",
    fontSize: 12,
    fontFamily: TYPE.display,
    fontWeight: 500,
    cursor: "pointer",
    marginTop: 7,
  },
  histRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 4px",
    borderBottom: `1px solid var(--p-hair)`,
    transition: "border-color 0.5s ease",
  },
  verdictBtns: { display: "flex", gap: 6, flexShrink: 0 },
  verdictYes: {
    background: "transparent",
    border: "1px solid",
    borderRadius: 20,
    padding: "5px 12px",
    fontSize: 12,
    fontFamily: TYPE.display,
    fontWeight: 500,
    cursor: "pointer",
  },
  verdictNo: {
    background: "transparent",
    border: "1px solid",
    borderRadius: 20,
    padding: "5px 12px",
    fontSize: 12,
    fontFamily: TYPE.display,
    fontWeight: 500,
    cursor: "pointer",
  },
  verdictTag: {
    fontFamily: TYPE.ui,
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
  },

  // ── Signing the record ────────────────────────────────
  signCard: {
    background: "var(--p-glass)",
    border: "1px solid var(--p-glassBorder)",
    borderRadius: 20,
    boxShadow: "var(--p-cardShadow)",
    padding: "18px 18px 16px",
    marginBottom: 16,
    textAlign: "left",
  },
  signTitle: {
    fontFamily: TYPE.display,
    fontSize: 22,
    fontWeight: 500,
    letterSpacing: "-0.01em",
    color: "var(--p-text)",
  },
  signSub: {
    fontFamily: TYPE.body,
    fontSize: 14,
    lineHeight: 1.5,
    color: "var(--p-text)",
    opacity: 0.7,
    margin: "6px 0 16px",
  },
  signLabel: {
    fontFamily: TYPE.ui,
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: "var(--p-text)",
    opacity: 0.6,
    marginBottom: 6,
  },
  signInput: {
    width: "100%",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid var(--p-rule)",
    padding: "6px 2px 10px",
    fontFamily: TYPE.body,
    fontSize: 19,
    color: "var(--p-text)",
    outline: "none",
    marginBottom: 14,
  },
  signError: {
    fontFamily: TYPE.body,
    fontSize: 12,
    color: "var(--p-accent)",
    margin: "-6px 0 10px",
  },
  signBtn: {
    width: "100%",
    background: "var(--p-ctaBg)",
    color: "var(--p-ctaGold)",
    border: "none",
    borderRadius: 100,
    padding: 15,
    fontFamily: TYPE.ui,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    cursor: "pointer",
  },
  signHint: {
    fontFamily: TYPE.body,
    fontSize: 12,
    color: "var(--p-text)",
    opacity: 0.5,
    textAlign: "center",
    marginTop: 10,
  },
  signedRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 4px",
    marginBottom: 14,
  },
  signedAs: {
    fontFamily: TYPE.body,
    fontSize: 12,
    color: "var(--p-text)",
    opacity: 0.6,
  },
  signOutBtn: {
    background: "transparent",
    border: "1px solid var(--p-hair)",
    borderRadius: 100,
    padding: "6px 14px",
    fontFamily: TYPE.ui,
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "var(--p-textSoft)",
    cursor: "pointer",
  },

  // ── Your Record (ported 2026-08-17) ───────────────────────────────────
  // The prototype's You: a ruled masthead, the rank worn as a disc, then the
  // record itself as ledger rows. Masthead furniture is shared with browse.js
  // (indexEyebrowRow / indexRule / indexEyebrow) so the book stays one book.
  recordHead: { textAlign: "center", padding: "6px 8px 0" },
  recordDisc: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    border: "1px solid var(--p-rule)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto",
    fontFamily: TYPE.display,
    fontSize: 22,
    color: "var(--p-accent)",
  },
  recordName: {
    fontFamily: TYPE.display,
    fontSize: 34,
    fontWeight: 500,
    letterSpacing: "-0.01em",
    lineHeight: 1.05,
    color: "var(--p-text)",
    margin: "14px 0 0",
  },
  recordSince: {
    fontFamily: TYPE.body,
    fontSize: 14,
    color: "var(--p-text)",
    opacity: 0.65,
    marginTop: 9,
  },
  recordTally: {
    fontFamily: TYPE.ui,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: "var(--p-accent)",
    marginTop: 12,
  },
  // Progress toward the next rank, quieter than the old crest.
  recordTrack: {
    height: 2,
    background: "var(--p-hair)",
    borderRadius: 2,
    margin: "14px auto 0",
    maxWidth: 180,
    overflow: "hidden",
  },
  recordFill: { height: "100%", borderRadius: 2 },
  recordNext: {
    fontFamily: TYPE.body,
    fontSize: 12,
    color: "var(--p-text)",
    opacity: 0.5,
    marginTop: 7,
  },

  // A cast, as a line in the record: title, when, leader, verdict.
  recordRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    padding: "11px 0",
    borderTop: "1px solid var(--p-hair)",
  },
  recordTitle: {
    fontFamily: TYPE.display,
    fontSize: 16,
    fontWeight: 500,
    color: "var(--p-text)",
    whiteSpace: "nowrap",
  },
  recordWhen: {
    fontFamily: TYPE.ui,
    fontSize: 10,
    fontWeight: 600,
    color: "var(--p-text)",
    opacity: 0.55,
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  recordEmpty: {
    fontFamily: TYPE.body,
    fontSize: 14,
    lineHeight: 1.5,
    color: "var(--p-text)",
    opacity: 0.65,
    textAlign: "center",
    padding: "14px 0 16px",
  },
});
